["Currency.EUR"]
few = "{{.count}} Euros"
hash = "sha1-926fb0c81dd926551dfaeaa278395250b88aede5"
many = "{{.count}} Euros"
one = "Euro"
other = "{{.count}} Euros"

["Currency.UAH"]
few = "{{.count}} Ukrainian Hryvnias"
hash = "sha1-92864e820bf64d9300551e5d0daaa2d444267877"
many = "{{.count}} Ukrainian Hryvnias"
one = "Ukrainian Hryvnia"
other = "{{.count}} Ukrainian Hryvnias"

["Currency.USD"]
few = "{{.count}} US Dollars"
hash = "sha1-63a3c0466ebb6eab5dc73c0d285c4aeb5b363ec6"
many = "{{.count}} US Dollars"
one = "US Dollar"
other = "{{.count}} US Dollars"

[mainTitle]
hash = "sha1-1acc06f88fd654a52d9f4209d1f55b7da4e3c302"
other = "CR.Today - Конвертер"
