package models

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

type Currency struct {
	Code   string
	Symbol string
	Flag   string
}

var Currencies = []Currency{
	{Code: "AFN", Symbol: "؋", Flag: "af"},
	{Code: "XCD", Symbol: "$", Flag: "oecs"},
	{Code: "KHR", Symbol: "៛", Flag: "kh"},
	{Code: "XAF", Symbol: "FCFA", Flag: "car"},
	{Code: "AUD", Symbol: "$", Flag: "au"},
	{Code: "EUR", Symbol: "€", Flag: "eu"},
	{Code: "XOF", Symbol: "₣", Flag: "ecowas"},
	{Code: "CUP", Symbol: "$", Flag: "cu"},
	{Code: "BDT", Symbol: "Tk", Flag: "bd"},
	{Code: "BRL", Symbol: "R$", Flag: "br"},
	{Code: "GEL", Symbol: "ლ", Flag: "ge"},
	{Code: "HTG", Symbol: "G", Flag: "ht"},
	{Code: "INR", Symbol: "Rs.", Flag: "in"},
	{Code: "ILS", Symbol: "₪", Flag: "il"},
	{Code: "KZT", Symbol: "KZT", Flag: "kz"},
	{Code: "KWD", Symbol: "د.ك", Flag: "kw"},
	{Code: "LSL", Symbol: "M", Flag: "ls"},
	{Code: "MYR", Symbol: "RM", Flag: "my"},
	{Code: "MUR", Symbol: "₨", Flag: "mu"},
	{Code: "MNT", Symbol: "₮", Flag: "mn"},
	{Code: "MMK", Symbol: "K", Flag: "mm"},
	{Code: "XPF", Symbol: "F", Flag: "xpf"},
	{Code: "WST", Symbol: "WS$", Flag: "ws"},
	{Code: "TZS", Symbol: "x", Flag: "tz"},
	{Code: "NOK", Symbol: "kr", Flag: "no"},
	{Code: "RSD", Symbol: "RSD", Flag: "rs"},
	{Code: "TND", Symbol: "د.ت", Flag: "tn"},
	{Code: "UZS", Symbol: "UZS", Flag: "uz"},
	{Code: "RWF", Symbol: "FRw", Flag: "rw"},
	{Code: "SEK", Symbol: "kr", Flag: "se"},
	{Code: "YER", Symbol: "YER", Flag: "ye"},
	{Code: "PGK", Symbol: "K", Flag: "pg"},
	{Code: "UAH", Symbol: "₴", Flag: "ua"},
	{Code: "DZD", Symbol: "دج", Flag: "dz"},
	{Code: "ARS", Symbol: "$", Flag: "ar"},
	{Code: "AZN", Symbol: "M", Flag: "az"},
	{Code: "BYN", Symbol: "Br", Flag: "by"},
	{Code: "BOB", Symbol: "Bs", Flag: "bo"},
	{Code: "BGN", Symbol: "лв", Flag: "bg"},
	{Code: "CAD", Symbol: "C$", Flag: "ca"},
	{Code: "CNY", Symbol: "¥", Flag: "cn"},
	{Code: "CRC", Symbol: "₡", Flag: "cr"},
	{Code: "CZK", Symbol: "Kc", Flag: "cz"},
	{Code: "USD", Symbol: "$", Flag: "us"},
	{Code: "GHS", Symbol: "GHS", Flag: "gh"},
	{Code: "GNF", Symbol: "₣", Flag: "gn"},
	{Code: "HKD", Symbol: "HK$", Flag: "hk"},
	{Code: "IRR", Symbol: "ريال", Flag: "ir"},
	{Code: "JMD", Symbol: "$", Flag: "jm"},
	{Code: "LAK", Symbol: "₭", Flag: "la"},
	{Code: "LYD", Symbol: "ل.د", Flag: "ly"},
	{Code: "MKD", Symbol: "MKD", Flag: "mk"},
	{Code: "NIO", Symbol: "C$", Flag: "ni"},
	{Code: "PKR", Symbol: "Rs.", Flag: "pk"},
	{Code: "PEN", Symbol: "S/.", Flag: "pe"},
	{Code: "QAR", Symbol: "ر.ق", Flag: "qa"},
	{Code: "STD", Symbol: "Db", Flag: "st"},
	{Code: "SLL", Symbol: "Le", Flag: "sl"},
	{Code: "SOS", Symbol: "Sh.So.", Flag: "so"},
	{Code: "SDG", Symbol: "SDG", Flag: "sd"},
	{Code: "SYP", Symbol: "LS", Flag: "sy"},
	{Code: "TMT", Symbol: "TMM", Flag: "tm"},
	{Code: "GBP", Symbol: "£", Flag: "gb"},
	{Code: "VES", Symbol: "Bs.S.", Flag: "ve"},
	{Code: "AMD", Symbol: "AMD", Flag: "am"},
	{Code: "BSD", Symbol: "$", Flag: "bs"},
	{Code: "BAM", Symbol: "КМ", Flag: "ba"},
	{Code: "KYD", Symbol: "$", Flag: "ky"},
	{Code: "ETB", Symbol: "Br", Flag: "et"},
	{Code: "IQD", Symbol: "ع.د", Flag: "iq"},
	{Code: "GIP", Symbol: "£", Flag: "gi"},
	{Code: "DKK", Symbol: "kr", Flag: "dk"},
	{Code: "COP", Symbol: "$", Flag: "co"},
	{Code: "EGP", Symbol: "LE", Flag: "eg"},
	{Code: "HUF", Symbol: "Ft", Flag: "hu"},
	{Code: "KPW", Symbol: "KPW", Flag: "kp"},
	{Code: "CHF", Symbol: "₣", Flag: "ch"},
	{Code: "MGA", Symbol: "Ar", Flag: "mg"},
	{Code: "MDL", Symbol: "MDL", Flag: "md"},
	{Code: "MAD", Symbol: "د.م.", Flag: "ma"},
	{Code: "NPR", Symbol: "₨", Flag: "np"},
	{Code: "PHP", Symbol: "₱", Flag: "ph"},
	{Code: "RON", Symbol: "L", Flag: "ro"},
	{Code: "SAR", Symbol: "ر.س", Flag: "sa"},
	{Code: "SGD", Symbol: "S$", Flag: "sg"},
	{Code: "ZAR", Symbol: "R", Flag: "za"},
	{Code: "SRD", Symbol: "$", Flag: "sr"},
	{Code: "TOP", Symbol: "TOP", Flag: "to"},
	{Code: "TWD", Symbol: "NT$", Flag: "tw"},
	{Code: "VND", Symbol: "₫", Flag: "vn"},
	{Code: "BBD", Symbol: "$", Flag: "bb"},
	{Code: "ALL", Symbol: "L", Flag: "al"},
	{Code: "BND", Symbol: "B$", Flag: "bn"},
	{Code: "BTN", Symbol: "Nu.", Flag: "bt"},
	{Code: "CLP", Symbol: "$", Flag: "cl"},
	{Code: "CDF", Symbol: "CDF", Flag: "cd"},
	{Code: "DOP", Symbol: "RD$", Flag: "do"},
	{Code: "ERN", Symbol: "Nfk", Flag: "er"},
	{Code: "HNL", Symbol: "L", Flag: "hn"},
	{Code: "GTQ", Symbol: "Q", Flag: "gt"},
	{Code: "IDR", Symbol: "Rp", Flag: "id"},
	{Code: "KES", Symbol: "KSh", Flag: "ke"},
	{Code: "MVR", Symbol: "Rf", Flag: "mv"},
	{Code: "MXN", Symbol: "$", Flag: "mx"},
	{Code: "LRD", Symbol: "$", Flag: "lr"},
	{Code: "MOP", Symbol: "¥", Flag: "mo"},
	{Code: "KGS", Symbol: "сом", Flag: "kg"},
	{Code: "NAD", Symbol: "N$", Flag: "na"},
	{Code: "NZD", Symbol: "$", Flag: "nz"},
	{Code: "SHP", Symbol: "SHP", Flag: "sh"},
	{Code: "PYG", Symbol: "₲", Flag: "py"},
	{Code: "SBD", Symbol: "$", Flag: "sb"},
	{Code: "OMR", Symbol: "ر.ع.", Flag: "om"},
	{Code: "SCR", Symbol: "SR", Flag: "sc"},
	{Code: "LKR", Symbol: "ரூ", Flag: "lk"},
	{Code: "THB", Symbol: "฿", Flag: "th"},
	{Code: "TRY", Symbol: "YTL", Flag: "tr"},
	{Code: "AED", Symbol: "Dh", Flag: "ae"},
	{Code: "ZMW", Symbol: "ZMK", Flag: "zm"},
	{Code: "VUV", Symbol: "VT", Flag: "vu"},
	{Code: "AOA", Symbol: "Kz", Flag: "ao"},
	{Code: "AWG", Symbol: "ƒ", Flag: "aw"},
	{Code: "BHD", Symbol: ".د.ب", Flag: "bh"},
	{Code: "BZD", Symbol: "$", Flag: "bz"},
	{Code: "BWP", Symbol: "P", Flag: "bw"},
	{Code: "BIF", Symbol: "₣", Flag: "bi"},
	{Code: "KMF", Symbol: "₣", Flag: "km"},
	{Code: "DJF", Symbol: "DJF", Flag: "dj"},
	{Code: "FJD", Symbol: "FJ$", Flag: "fj"},
	{Code: "GMD", Symbol: "GMD", Flag: "gm"},
	{Code: "ISK", Symbol: "kr", Flag: "is"},
	{Code: "GYD", Symbol: "$", Flag: "gy"},
	{Code: "KRW", Symbol: "₩", Flag: "kr"},
	{Code: "JOD", Symbol: "JOD", Flag: "jo"},
	{Code: "MWK", Symbol: "MK", Flag: "mw"},
	{Code: "LBP", Symbol: "ل.ل", Flag: "lb"},
	{Code: "NGN", Symbol: "₦", Flag: "ng"},
	{Code: "MRO", Symbol: "MRO", Flag: "mr"},
	{Code: "TJS", Symbol: "TJS", Flag: "tj"},
	{Code: "PLN", Symbol: "zł", Flag: "pl"},
	{Code: "UYU", Symbol: "UYU", Flag: "uy"},
	{Code: "MZN", Symbol: "MZM", Flag: "mz"},
	{Code: "SZL", Symbol: "SZL", Flag: "sz"},
	{Code: "TTD", Symbol: "TTD", Flag: "tt"},
	{Code: "PAB", Symbol: "B/.", Flag: "pa"},
	{Code: "UGX", Symbol: "USh", Flag: "ug"},
}

var Messages = []*i18n.Message{
	{ID: "Currency.AFN", One: "Afghan afghani", Other: "{{.count}} Afghan afghanis"},
	{ID: "Currency.XCD", One: "East Caribbean dollar", Other: "{{.count}} East Caribbean dollars"},
	{ID: "Currency.KHR", One: "Cambodian riel", Other: "{{.count}} Cambodian riels"},
	{ID: "Currency.XAF", One: "Central African CFA franc", Other: "{{.count}} Central African CFA francs"},
	{ID: "Currency.AUD", One: "Australian dollar", Other: "{{.count}} Australian dollars"},
	{ID: "Currency.EUR", One: "Euro", Other: "{{.count}} Euros"},
	{ID: "Currency.XOF", One: "West African CFA franc", Other: "{{.count}} West African CFA francs"},
	{ID: "Currency.CUP", One: "Cuban peso", Other: "{{.count}} Cuban pesos"},
	{ID: "Currency.BDT", One: "Bangladeshi taka", Other: "{{.count}} Bangladeshi takas"},
	{ID: "Currency.BRL", One: "Brazilian real", Other: "{{.count}} Brazilian reals"},
	{ID: "Currency.GEL", One: "Georgian lari", Other: "{{.count}} Georgian laris"},
	{ID: "Currency.HTG", One: "Haitian gourde", Other: "{{.count}} Haitian gourdes"},
	{ID: "Currency.INR", One: "Indian rupee", Other: "{{.count}} Indian rupees"},
	{ID: "Currency.ILS", One: "Israeli new sheqel", Other: "{{.count}} Israeli new sheqels"},
	{ID: "Currency.KZT", One: "Kazakhstani tenge", Other: "{{.count}} Kazakhstani tenges"},
	{ID: "Currency.KWD", One: "Kuwaiti dinar", Other: "{{.count}} Kuwaiti dinars"},
	{ID: "Currency.LSL", One: "Lesotho loti", Other: "{{.count}} Lesotho lotis"},
	{ID: "Currency.MYR", One: "Malaysian ringgit", Other: "{{.count}} Malaysian ringgits"},
	{ID: "Currency.MUR", One: "Mauritian rupee", Other: "{{.count}} Mauritian rupees"},
	{ID: "Currency.MNT", One: "Mongolian tugrik", Other: "{{.count}} Mongolian tugriks"},
	{ID: "Currency.MMK", One: "Myanma kyat", Other: "{{.count}} Myanma kyats"},
	{ID: "Currency.XPF", One: "CFP franc", Other: "{{.count}} CFP francs"},
	{ID: "Currency.WST", One: "Samoan tala", Other: "{{.count}} Samoan talas"},
	{ID: "Currency.TZS", One: "Tanzanian shilling", Other: "{{.count}} Tanzanian shillings"},
	{ID: "Currency.NOK", One: "Norwegian krone", Other: "{{.count}} Norwegian kroner"},
	{ID: "Currency.RSD", One: "Serbian dinar", Other: "{{.count}} Serbian dinars"},
	{ID: "Currency.TND", One: "Tunisian dinar", Other: "{{.count}} Tunisian dinars"},
	{ID: "Currency.UZS", One: "Uzbekistani som", Other: "{{.count}} Uzbekistani soms"},
	{ID: "Currency.RWF", One: "Rwandan franc", Other: "{{.count}} Rwandan francs"},
	{ID: "Currency.SEK", One: "Swedish krona", Other: "{{.count}} Swedish kronor"},
	{ID: "Currency.YER", One: "Yemeni rial", Other: "{{.count}} Yemeni rials"},
	{ID: "Currency.PGK", One: "Papua New Guinean kina", Other: "{{.count}} Papua New Guinean kinas"},
	{ID: "Currency.UAH", One: "Ukrainian hryvnia", Other: "{{.count}} Ukrainian hryvnias"},
	{ID: "Currency.DZD", One: "Algerian dinar", Other: "{{.count}} Algerian dinars"},
	{ID: "Currency.ARS", One: "Argentine peso", Other: "{{.count}} Argentine pesos"},
	{ID: "Currency.AZN", One: "Azerbaijani manat", Other: "{{.count}} Azerbaijani manats"},
	{ID: "Currency.BYN", One: "Belarusian ruble", Other: "{{.count}} Belarusian rubles"},
	{ID: "Currency.BOB", One: "Bolivian boliviano", Other: "{{.count}} Bolivian bolivianos"},
	{ID: "Currency.BGN", One: "Bulgarian lev", Other: "{{.count}} Bulgarian leva"},
	{ID: "Currency.CAD", One: "Canadian dollar", Other: "{{.count}} Canadian dollars"},
	{ID: "Currency.CNY", One: "Chinese renminbi", Other: "{{.count}} Chinese renminbis"},
	{ID: "Currency.CRC", One: "Costa Rican colon", Other: "{{.count}} Costa Rican colones"},
	{ID: "Currency.CZK", One: "Czech koruna", Other: "{{.count}} Czech korunas"},
	{ID: "Currency.USD", One: "US Dollar", Other: "{{.count}} US Dollars"},
	{ID: "Currency.GHS", One: "Ghanaian cedi", Other: "{{.count}} Ghanaian cedis"},
	{ID: "Currency.GNF", One: "Guinean franc", Other: "{{.count}} Guinean francs"},
	{ID: "Currency.HKD", One: "Hong Kong dollar", Other: "{{.count}} Hong Kong dollars"},
	{ID: "Currency.IRR", One: "Iranian rial", Other: "{{.count}} Iranian rials"},
	{ID: "Currency.JMD", One: "Jamaican dollar", Other: "{{.count}} Jamaican dollars"},
	{ID: "Currency.LAK", One: "Lao kip", Other: "{{.count}} Lao kips"},
	{ID: "Currency.LYD", One: "Libyan dinar", Other: "{{.count}} Libyan dinars"},
	{ID: "Currency.MKD", One: "Macedonian denar", Other: "{{.count}} Macedonian denars"},
	{ID: "Currency.NIO", One: "Nicaraguan cordoba", Other: "{{.count}} Nicaraguan cordobas"},
	{ID: "Currency.PKR", One: "Pakistani rupee", Other: "{{.count}} Pakistani rupees"},
	{ID: "Currency.PEN", One: "Peruvian nuevo sol", Other: "{{.count}} Peruvian nuevos soles"},
	{ID: "Currency.QAR", One: "Qatari riyal", Other: "{{.count}} Qatari riyals"},
	{ID: "Currency.STD", One: "Sao Tome and Principe dobra", Other: "{{.count}} Sao Tome and Principe dobras"},
	{ID: "Currency.SLL", One: "Sierra Leonean leone", Other: "{{.count}} Sierra Leonean leones"},
	{ID: "Currency.SOS", One: "Somali shilling", Other: "{{.count}} Somali shillings"},
	{ID: "Currency.SDG", One: "Sudanese pound", Other: "{{.count}} Sudanese pounds"},
	{ID: "Currency.SYP", One: "Syrian pound", Other: "{{.count}} Syrian pounds"},
	{ID: "Currency.TMT", One: "Turkmen manat", Other: "{{.count}} Turkmen manats"},
	{ID: "Currency.GBP", One: "British pound", Other: "{{.count}} British pounds"},
	{ID: "Currency.VES", One: "Venezuelan bolívar soberano", Other: "{{.count}} Venezuelan bolívar soberanos"},
	{ID: "Currency.AMD", One: "Armenian dram", Other: "{{.count}} Armenian drams"},
	{ID: "Currency.BSD", One: "Bahamian dollar", Other: "{{.count}} Bahamian dollars"},
	{ID: "Currency.BAM", One: "Bosnia and Herzegovina marka", Other: "{{.count}} Bosnia and Herzegovina markas"},
	{ID: "Currency.KYD", One: "Cayman Islands dollar", Other: "{{.count}} Cayman Islands dollars"},
	{ID: "Currency.ETB", One: "Ethiopian birr", Other: "{{.count}} Ethiopian birrs"},
	{ID: "Currency.IQD", One: "Iraqi dinar", Other: "{{.count}} Iraqi dinars"},
	{ID: "Currency.GIP", One: "Gibraltar pound", Other: "{{.count}} Gibraltar pounds"},
	{ID: "Currency.DKK", One: "Danish krone", Other: "{{.count}} Danish kroner"},
	{ID: "Currency.COP", One: "Colombian peso", Other: "{{.count}} Colombian pesos"},
	{ID: "Currency.EGP", One: "Egyptian pound", Other: "{{.count}} Egyptian pounds"},
	{ID: "Currency.HUF", One: "Hungarian forint", Other: "{{.count}} Hungarian forints"},
	{ID: "Currency.KPW", One: "North Korean won", Other: "{{.count}} North Korean won"},
	{ID: "Currency.CHF", One: "Swiss franc", Other: "{{.count}} Swiss francs"},
	{ID: "Currency.MGA", One: "Malagasy ariary", Other: "{{.count}} Malagasy ariaries"},
	{ID: "Currency.MDL", One: "Moldovan leu", Other: "{{.count}} Moldovan lei"},
	{ID: "Currency.MAD", One: "Moroccan dirham", Other: "{{.count}} Moroccan dirhams"},
	{ID: "Currency.NPR", One: "Nepalese rupee", Other: "{{.count}} Nepalese rupees"},
	{ID: "Currency.PHP", One: "Philippine peso", Other: "{{.count}} Philippine pesos"},
	{ID: "Currency.RON", One: "Romanian leu", Other: "{{.count}} Romanian lei"},
	{ID: "Currency.SAR", One: "Saudi riyal", Other: "{{.count}} Saudi riyals"},
	{ID: "Currency.SGD", One: "Singapore dollar", Other: "{{.count}} Singapore dollars"},
	{ID: "Currency.ZAR", One: "South African rand", Other: "{{.count}} South African rand"},
	{ID: "Currency.SRD", One: "Surinamese dollar", Other: "{{.count}} Surinamese dollars"},
	{ID: "Currency.TOP", One: "Pa'anga", Other: "{{.count}} Pa'angas"},
	{ID: "Currency.TWD", One: "New Taiwan dollar", Other: "{{.count}} New Taiwan dollars"},
	{ID: "Currency.VND", One: "Vietnamese dong", Other: "{{.count}} Vietnamese dongs"},
	{ID: "Currency.BBD", One: "Barbadian dollar", Other: "{{.count}} Barbadian dollars"},
	{ID: "Currency.ALL", One: "Albanian lek", Other: "{{.count}} Albanian leks"},
	{ID: "Currency.BND", One: "Brunei dollar", Other: "{{.count}} Brunei dollars"},
	{ID: "Currency.BTN", One: "Bhutanese ngultrum", Other: "{{.count}} Bhutanese ngultrums"},
	{ID: "Currency.CLP", One: "Chilean peso", Other: "{{.count}} Chilean pesos"},
	{ID: "Currency.CDF", One: "Congolese franc", Other: "{{.count}} Congolese francs"},
	{ID: "Currency.DOP", One: "Dominican peso", Other: "{{.count}} Dominican pesos"},
	{ID: "Currency.ERN", One: "Eritrean nakfa", Other: "{{.count}} Eritrean nakfas"},
	{ID: "Currency.HNL", One: "Honduran lempira", Other: "{{.count}} Honduran lempiras"},
	{ID: "Currency.GTQ", One: "Guatemalan quetzal", Other: "{{.count}} Guatemalan quetzals"},
	{ID: "Currency.IDR", One: "Indonesian rupiah", Other: "{{.count}} Indonesian rupiahs"},
	{ID: "Currency.KES", One: "Kenyan shilling", Other: "{{.count}} Kenyan shillings"},
	{ID: "Currency.MVR", One: "Maldivian rufiyaa", Other: "{{.count}} Maldivian rufiyaas"},
	{ID: "Currency.MXN", One: "Mexican peso", Other: "{{.count}} Mexican pesos"},
	{ID: "Currency.LRD", One: "Liberian dollar", Other: "{{.count}} Liberian dollars"},
	{ID: "Currency.MOP", One: "Macanese pataca", Other: "{{.count}} Macanese patacas"},
	{ID: "Currency.KGS", One: "Kyrgyzstani som", Other: "{{.count}} Kyrgyzstani soms"},
	{ID: "Currency.NAD", One: "Namibian dollar", Other: "{{.count}} Namibian dollars"},
	{ID: "Currency.NZD", One: "New Zealand dollar", Other: "{{.count}} New Zealand dollars"},
	{ID: "Currency.SHP", One: "Saint Helena pound", Other: "{{.count}} Saint Helena pounds"},
	{ID: "Currency.PYG", One: "Paraguayan guarani", Other: "{{.count}} Paraguayan guaranis"},
	{ID: "Currency.SBD", One: "Solomon Islands dollar", Other: "{{.count}} Solomon Islands dollars"},
	{ID: "Currency.OMR", One: "Omani rial", Other: "{{.count}} Omani rials"},
	{ID: "Currency.SCR", One: "Seychellois rupee", Other: "{{.count}} Seychellois rupees"},
	{ID: "Currency.LKR", One: "Sri Lankan rupee", Other: "{{.count}} Sri Lankan rupees"},
	{ID: "Currency.THB", One: "Thai baht", Other: "{{.count}} Thai bahts"},
	{ID: "Currency.TRY", One: "Turkish lira", Other: "{{.count}} Turkish liras"},
	{ID: "Currency.AED", One: "UAE dirham", Other: "{{.count}} UAE dirhams"},
	{ID: "Currency.ZMW", One: "Zambian kwacha", Other: "{{.count}} Zambian kwachas"},
	{ID: "Currency.VUV", One: "Vanuatu vatu", Other: "{{.count}} Vanuatu vatus"},
	{ID: "Currency.AOA", One: "Angolan kwanza", Other: "{{.count}} Angolan kwanzas"},
	{ID: "Currency.AWG", One: "Aruban florin", Other: "{{.count}} Aruban florins"},
	{ID: "Currency.BHD", One: "Bahraini dinar", Other: "{{.count}} Bahraini dinars"},
	{ID: "Currency.BZD", One: "Belize dollar", Other: "{{.count}} Belize dollars"},
	{ID: "Currency.BWP", One: "Botswana pula", Other: "{{.count}} Botswana pulas"},
	{ID: "Currency.BIF", One: "Burundian franc", Other: "{{.count}} Burundian francs"},
	{ID: "Currency.KMF", One: "Comorian franc", Other: "{{.count}} Comorian francs"},
	{ID: "Currency.DJF", One: "Djiboutian franc", Other: "{{.count}} Djiboutian francs"},
	{ID: "Currency.FJD", One: "Fijian dollar", Other: "{{.count}} Fijian dollars"},
	{ID: "Currency.GMD", One: "Gambian dalasi", Other: "{{.count}} Gambian dalasis"},
	{ID: "Currency.ISK", One: "Icelandic króna", Other: "{{.count}} Icelandic krónur"},
	{ID: "Currency.GYD", One: "Guyanese dollar", Other: "{{.count}} Guyanese dollars"},
	{ID: "Currency.KRW", One: "South Korean won", Other: "{{.count}} South Korean won"},
	{ID: "Currency.JOD", One: "Jordanian dinar", Other: "{{.count}} Jordanian dinars"},
	{ID: "Currency.MWK", One: "Malawian kwacha", Other: "{{.count}} Malawian kwachas"},
	{ID: "Currency.LBP", One: "Lebanese pound", Other: "{{.count}} Lebanese pounds"},
	{ID: "Currency.NGN", One: "Nigerian naira", Other: "{{.count}} Nigerian nairas"},
	{ID: "Currency.MRO", One: "Mauritanian ouguiya", Other: "{{.count}} Mauritanian ouguiyas"},
	{ID: "Currency.TJS", One: "Tajikistani somoni", Other: "{{.count}} Tajikistani somonis"},
	{ID: "Currency.PLN", One: "Polish zloty", Other: "{{.count}} Polish zlotys"},
	{ID: "Currency.UYU", One: "Uruguayan peso", Other: "{{.count}} Uruguayan pesos"},
	{ID: "Currency.MZN", One: "Mozambican metical", Other: "{{.count}} Mozambican meticals"},
	{ID: "Currency.SZL", One: "Swazi lilangeni", Other: "{{.count}} Swazi emalangeni"},
	{ID: "Currency.TTD", One: "Trinidad and Tobago dollar", Other: "{{.count}} Trinidad and Tobago dollars"},
	{ID: "Currency.PAB", One: "Panamanian balboa", Other: "{{.count}} Panamanian balboas"},
	{ID: "Currency.UGX", One: "Ugandan shilling", Other: "{{.count}} Ugandan shillings"},
}
